### ISSUE TITLE
Unexpected value 'JsonApiModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by supertino7** [ghidoz/angular2-jsonapi#36]
After upgrading to v3.2, I've got this error message : 

`
client?8fb9:75 ./client/app/app.module.ts
(5,31): error TS2307: Cannot find module 'angular2-jsonapi'.
`
`
compiler.umd.js?9df7:13996 Uncaught Error: Unexpected value 'JsonApiModule' imported by the module 'AppModule'
`

I tried to change the position of the import at the top of my app.module.ts, and in the imports[] of my ngModule. No success.

Also tried the fix proposed in #13 and related issues : 
`
module.exports = {
  resolve: { 
    modules: [ path.join(__dirname, "node_modules") ]
  }
};
`

Doesn't work either.
Note that the "Unexpected value" displays only in Chrome console, not in my build process.

I use Webpack 1.13.2, but not angular-cli, my project boilerplate is created from scratch.

Thx for your help.

**Comment by supertino7** [comment]
I downgraded to v3.1.0 and the error messages disappeared... So there's something from v3.1.1 that causes that issue
