### ISSUE TITLE
Migration rxjs 6

### ISSUE THREAD

**Issue by zeevkatz** [ghidoz/angular2-jsonapi#171]
I'm using **rxjs@6** and it's seems like the peerDependencies expects to work with **>=5.2.0**.
Would it be possible to migrate **rxjs** from **5.2.0** to **6** ?

One of the errors that I accept:
`node_modules/angular2-jsonapi/dist/services/json-api-datastore.service.d.ts(40,40): error TS2314: Generic type 'ErrorObservable<T>' requires 1 type argument(s).`

Thanks!

**Comment by hpawe01** [comment]
Hey @zeevkatz,

I see, that you created a pull request to fix this issue (#172). Could you add some tests for the new code line, so that the checks succeed? Then it would be easy for e.g. @HennerM to merge this pull request.

Thanks

**Comment by zeevkatz** [comment]
I’ll remove this pull request and create a new one. There are a few things that can be written better and I’ll write the necessary tests on the way.

**Comment by hpawe01** [comment]
@zeevkatz thanks for your pull request (#180). 

I added some comments, but we need either @HennerM or @safo6m to approve this.

**Comment by safo6m** [comment]
Angular2-jsonapi v6.0.0-beta is compatible with rxjs@6.
@hpawe01 please re-open the issue if you encounter any additional problems.
